baseURL                          = "https://example.org/"
theme                            = "introduction"
DefaultContentLanguage           = "en"

[params]
    themeStyle                   = "auto"
    favicon                      = "/img/fav.ico"
    showMenu                     = true
    showRSSButton                = false
    fadeIn                       = true
    fadeInIndex                  = false
    dateFormat                   = "Jan 2, 2006"
    email                        = "youremail@email.com"

    [params.home]
        introHeight              = "fullheight"
        showLatest               = true
        showAllPosts             = false
        allPostsArchiveFormat    = true
        numberOfProjectsToShow   = 3
        localTime                = true
        timeZone                 = "America/Los_Angeles"
        timeFormat               = "en-US"

    [params.projects]
        useTwoColumns            = false

    [params.share]
        twitter                  = true
        facebook                 = true
        pinterest                = true

    [[params.social]]
        url   = "https://twitter.com/"
        icon  = "twitter"
        icon_pack = "fab"
    [[params.social]]
        url   = "https://linkedin.com/"
        icon  = "linkedin-in"
        icon_pack = "fab"
    [[params.social]]
        url = "mailto:youremail@email.com"
        icon = "paper-plane"
        icon_pack = "fas"

[taxonomies]
  tag = "tags"
  series = "series"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    style = "solarized-dark"
    tabWidth = 4

[languages]
    [languages.en]
        languageName     = "English"
        languageCode     = "en-us"
        contentDir       = "content/en"
        weight           = 0
        title            = "My Site"
        [languages.en.params]
            description  = "My personal website"
