baseURL                          = "https://odmarden.github.io/"
theme                            = "introduction"
DefaultContentLanguage           = "sv"

[params]
    themeStyle                   = "auto"
    favicon                      = "/img/fav.ico"
    showMenu                     = true
    showRSSButton                = false
    fadeIn                       = true
    fadeInIndex                  = false
    dateFormat                   = "2 Jan 2006"
    email                        = "daniel@wiklander.biz"

    [params.home]
        introHeight              = "fullheight"
        showLatest               = true
        showAllPosts             = false
        allPostsArchiveFormat    = true
        numberOfProjectsToShow   = 3
        localTime                = false

    [params.projects]
        useTwoColumns            = false

    [params.share]
        twitter                  = true
        facebook                 = true
        pinterest                = true

    [[params.social]]
        url   = "https://www.linkedin.com/in/daniel-wiklander-15b7202a"
        icon  = "linkedin-in"
        icon_pack = "fab"
    [[params.social]]
        url = "mailto:daniel@wiklander.biz"
        icon = "paper-plane"
        icon_pack = "fas"

[taxonomies]
  tag = "tags"
  series = "series"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    style = "solarized-dark"
    tabWidth = 4

[languages]
    [languages.sv]
        languageName     = "Svenska"
        languageCode     = "sv"
        contentDir       = "content/sv"
        weight           = 0
        title            = "Daniel Wiklander"
        [languages.sv.params]
            description  = "Daniel Wiklanders sajt"
